development:
  
  soundcloud:
    key: devkey
    secret: devsecret
    base_url: http://api.soundcloud.com
  
  twitter:
    key: devkey
    secret: devsecret
    base_url: https://twitter.com
  
  facebook:
    app_id: devappid
    secret: devsecret
    base_url: https://graph.facebook.com
    
  myspace:
    key: devkey
    secret: devsecret
    base_url: http://api.myspace.com    
    
  digg:
    key: devkey
    secret: devsecret
    base_url: http://digg.com

test:
  
  soundcloud:
    key: testkey
    secret: testsecret
    base_url: http://api.soundcloud.com
  
  twitter:
    key: testkey
    secret: testsecret
    base_url: https://twitter.com
  
  facebook:
    app_id: testappid
    secret: testsecret
    base_url: https://graph.facebook.com
    
  myspace:
    key: testkey
    secret: testsecret
    base_url: http://api.myspace.com    
    
  digg:
    key: testkey
    secret: testsecret
    base_url: http://digg.com

production:
  
  soundcloud:
    key: e452ef9c6a1fa6b5963db114902c66aa
    secret: fed3d157c022e6d20bd987e8ce14c185
    base_url: http://api.soundcloud.com
  
  twitter:
    key: prokey
    secret: prosecret
    base_url: https://twitter.com
  
  facebook:
    app_id: 657454184366677
    secret: e7c2f4b04dd955fdae2dbe5daf059a54
    base_url: https://graph.facebook.com
    
  myspace:
    key: prokey
    secret: prosecret
    base_url: http://api.myspace.com    
    
  digg:
    key: prokey
    secret: prosecre
    base_url: http://digg.com
